const BOOT = 'BOOT';

const DISMOUNT_GAME = 'DISMOUNT_GAME';

const SAVE_PROGRESS = 'SAVE-PROGRESS';

const REQUEST_PINYIN_START = 'REQUEST_PINYIN_START';

const REQUEST_PINYIN_END = 'REQUEST_PINYIN_END';

const REVEAL_FLASHCARD = 'REVEAL-FLASHCARD';

const GUESS_FLASHCARD_RIGHT = 'GUESS_FLASHCARD_RIGHT';

const GUESS_FLASHCARD_WRONG = 'GUESS_FLASHCARD_WRONG';

const START_ROUND = 'START_ROUND';

const END_ROUND = 'END_ROUND';

const CHEAT_ANSWER_ALL = 'CHEAT_ANSWER_ALL';

const INIT = 'INIT';

const INIT_END = 'INIT_END';

const FLIP_CARDS_END = 'FLIP_CARDS_END';

const FLIP_CARDS_START = 'FLIP_CARDS_START';

const DESELECT_ALL_UNANSWERED_CARDS = 'DESELECT_ALL_UNANSWERED_CARDS';

const SWITCH_GAME = 'SWITCH_GAME';

const SAVE_COMPLETE = 'SAVE_COMPLETE';

const HIGHLIGHT_CHARACTER = 'HIGHLIGHT_CHAR';

export default {
    INIT,
    INIT_END,
    BOOT,
    HIGHLIGHT_CHARACTER,
    CHEAT_ANSWER_ALL,
    RENDER_COMPLETE: 'RENDER_COMPLETE',
    DISMOUNT_DECK: 'DISMOUNT_DECK',
    RESET_CURRENT_DECK: 'RESET_CURRENT_DECK',
    DISMOUNT_GAME,
    FLIP_CARDS_START,
    FLIP_CARDS_END,
    SAVE_COMPLETE,
    DESELECT_ALL_UNANSWERED_CARDS,
    START_ROUND,
    END_ROUND,
    SWITCH_GAME,
    GUESS_FLASHCARD_RIGHT,
    GUESS_FLASHCARD_WRONG,
    REVEAL_FLASHCARD,
    REQUEST_PINYIN_START,
    REQUEST_PINYIN_END,
    SAVE_PROGRESS,
    SET_DECK: 'SET_DECK'
};
